# Generated by Django 2.2.7 on 2019-12-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
